sudo: false
language: python
python: 3.8

matrix:
  include:
    - name: Schema validation tests
      env: TOXENV=py38
    - name: Check Python files with black autoformatter
      env: TOXENV=black
    - name: Check Python files with flake8
      env: TOXENV=flake8
    - name: Build documentation
      env: TOXENV=docs
      addons:
        apt:
          packages:
            - graphviz

install:
    - pip install tox
script: tox
